### PR TITLE
Add Stretchable Image

### PR DESCRIPTION
**Pull request by alexch2000**
Add ability to fill with stretchable image. 
Very useful for bar plot!

### CODE REVIEW

**Comment by mike-lischke** [comment]
Can you add an image showing the new feature?

**Comment by alexch2000** [comment]
Yes, sure! We use Core Plot to render such graph with stretchable images

**Comment by mike-lischke** [comment]
Ah, cool. So you are using a circle image and stretch it over the entire bar?

**Comment by alexch2000** [comment]
Yes. Exactly.

Here it is:
violet_dot

**Comment by eskroch** [comment]
`CPTImage` already supports stretchable images as of release 1.6. Does that not work for fills?

`CPTFill` is a class cluster. If `_CPTFillImage` doesn't handle stretchable images correctly, the change should be made there. If that won't work for some reason, the stretchable image class should be a private class that is part of the cluster.

**Comment by alexch2000** [comment]
Ok, thanks for your comment. I will try to fix it there

**Pull request closed without merging**
