### PR TITLE
Release 2.3

### PR DESCRIPTION
**Pull request by jterry94**
Please consider the following issues before submitting a pull request:

-[] Support all platforms (Mac, iOS, and tvOS)
-[] Pass Travis build validation
-[] Include unit tests where appropriate
-[] If adding a new feature, consider including a demo in the *Plot Gallery* example app

### CODE REVIEW

**Comment by jterry94** [comment]
Hi All, 

Sorry about the poor attempt at uploading to the previous pull request. I'm new to GitHub. 

I have adjusted my example a bit based upon feedback from students. Here is another attempt at uploading a Mac Swift Example of a scatter plot. 

[Swift Plotting Example.zip](https://github.com/core-plot/core-plot/files/786360/Swift.Plotting.Example.zip)

Jeff

**Comment by eskroch** [comment]
I made a few changes to the attached app code. I removed some dead code and streamlined other parts to make it easier to follow. I also added constraints to the hosting view so it resizes with the window.

Although it is different in several ways, I'm not sure this adds much beyond the existing Mac example app (*DatePlot*). For now, I'm not going add it to the Core Plot repository. If you expand it further to demonstrate more complex formatting options and/or other plot types, I'll reconsider.

[Swift Plotting Example Updated.zip](https://github.com/core-plot/core-plot/files/908361/Swift.Plotting.Example.Updated.zip)

**Comment by jterry94** [comment]
Ok. No worries. I will pass this along to my students. They had trouble using DatePlot so that's why I put this together. 

Quick question is there any way to rotate the text vertically? So the y axis label would appear "correctly. "

Jeff

**Comment by eskroch** [comment]
Set the `transform` property of the text layer for the label to a rotation matrix. For example:

    textLayer.transform = CATransform3DMakeRotation( angle, 0.0, 0.0, 1.0 )

Instead of annotations, you could also set the `title` for each axis. The default settings make the title float in the middle of the visible axis range; set the `titleLocation` to fix it at one position.

**Comment by jterry94** [comment]
Thanks. 

Jeff

**Comment by jterry94** [comment]
Hi Eric, 

Hi Eric, 

I am preparing for my class next semester and trying to update the plotting program to allow rotated text. 

As you suggested, I trying the CATransform3DMakeRotation as in the code below.

Unfortunately, it does not rotate the text. Am I missing something. 

Jeff
 

        let annY = CPTLayerAnnotation.init(anchorLayer: hostingView.hostedGraph!.plotAreaFrame!)

        annY.rectAnchor = .left; // to make it the top centre of the plotFrame
        annY.displacement = CGPoint(x: 50.0, y: 30.0) // To move it down, below the title

        let textLayerY = CPTTextLayer.init(text: yLabel, style: theTextStyle)
        let angle = CGFloat.pi/4.0
        
        textLayerY.transform = CATransform3DMakeRotation(angle, 0.0, 0.0, 1.0)

        annY.contentLayer = textLayerY
        
        hostingView.hostedGraph?.plotAreaFrame?.addAnnotation(annY)

**Comment by eskroch** [comment]
Use the annotation's `rotation` property to set the rotation angle rather than setting the `transform` directly. Core Plot resets the `transform` automatically during layout.

**Comment by jterry94** [comment]
Thanks,


Jeff

**Pull request closed without merging**
